version: '3'

tasks:
  generate:
    desc: "Generate Go gRPC code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=.
    silent: true
